name: White sur White
favicon: null
layout_spectrum: 0.9461066457442939
typography_spectrum: 0.19532725983299315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4f8'
    - '#cbcfc6'
    - '#859093'
    - '#000000'
    - '#5c411e'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
